sudo: required

services:
  - docker

before_install:
  - docker build -t shingidad/docker-react -f Dockerfile .

script:
  - docker run shingidad/docker-react

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-109142744568"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KET"