sudo: required

services:
  - docker

before_install:
  - docker build -t shingidad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shingidad/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-ap-northeast-2-109142744568"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_acces_key: "$AWS_SECRET_KEY"
